# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "A project for learning about edge computing."
language = "javascript"
manifest_version = 3
name = "Hello Compute"
service_id = "i2sxxldQ3dLBnfY1L6lnf5"

[local_server]

  [local_server.backends]

    [local_server.backends.website]
      url = "http://localhost:4173/"

[scripts]
  build = "npm run build"
  post_init = "npm install"

[setup]

  [setup.backends]

    [setup.backends.website]
      address = "SueSmith-hello-compute-origin.edgecompute.app"
